server:
  port: 7001
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称   这是ip地址吧？？？
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心,职责是维护服务实例(eureka服务器内需要添加common-api,不然provider怎么将服务注册到eureka),并不去检索服务
    fetch-registry: false
    #设置与 eureka-server 交互的地址,查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
